### ISSUE TITLE
Where to create the clientID?

### ISSUE THREAD

**Issue by rebeloper** [subdan/grid-collage#1]
Hi, 

Thanks for open sourcing your work. already learned a ton by looking at your code.
Could you specify where you created the "api_key"? Was it at:

https://www.instagram.com/developer/

I am new to the Instagram API. Any help is appreciated.

Thank you.

**Comment by subdan** [comment]
Hi.

1. Go to [Manage Clients](https://www.instagram.com/developer/clients/manage/).
2. Click Register a New Client
3. Fill app data
4. Click Register
5. Go to [Manage Clients](https://www.instagram.com/developer/clients/manage/).
6. You will see here Client ID you are looking for.
7. Click MANAGE
8. Go to Security tab
9. You need to specify Valid redirect URIs.
I set as https://subdan.ru/oauth
It should not be a real URL.
10. Change redirect_uri and redirectHost inside [InstagramURLBuilder.swift](https://github.com/subdan/grid-collage/blob/3d955852cb256d51b7b3ffb7dd5c54a67c2d7310/GridCollage/Helpers/InstagramURLBuilder.swift#L20) from my to your URL from step 9.

If you have any issues feel free to leave a comment.

**Comment by rebeloper** [comment]
Wow, your reply was super fast. Thank you very much. Consider adding it to the README file too. Will go through the steps first thing in the morning

**Comment by rebeloper** [comment]
As a final step I needed to uncheck "Disable implicit OAuth":
11. Uncheck "Disable implicit OAuth"
12. Click "Update Client"
